import Config

{:ok, addrs} = :inet.getifaddrs()

lan_ip =
  addrs
  |> Enum.flat_map(fn {_iface, opts} -> Keyword.get_values(opts, :addr) end)
  |> Enum.find(fn
    {a, _b, _, _} when a in [192, 10] -> true
    {172, b, _, _} when b >= 16 and b <= 31 -> true
    _ -> false
  end)
  |> then(fn
    nil -> "localhost"
    ip -> ip |> Tuple.to_list() |> Enum.join(".")
  end)

# Database connection disabled - uncomment if needed
# config :songy, Songy.Repo,
#   username: "postgres",
#   password: "postgres",
#   hostname: "localhost",
#   database: "songy_dev",
#   stacktrace: true,
#   show_sensitive_data_on_connection_error: true,
#   pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :songy, SongyWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "D4ZJEvFP19Dn0Mpzog0xd6QL5qu8RJUNfWmGRXf7447sfWh67sHftKl8uUSLtGFw",
  watchers: [
    vite: {Bun, :install_and_run, [:vite, ~w(dev)]}
  ],
  static_url: [host: lan_ip, port: String.to_integer(System.get_env("VITE_PORT") || "5173")]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :songy, SongyWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/songy_web/.*\.(ex|heex)$",
      ~r"lib/songy/.*\.(ex|exs)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :songy, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
