[request_definition]
r = sub, state, phase, act

[policy_definition]
p = sub, state, phase, act

[role_definition]
g = _, _

[matchers]
m = r.state == p.state && globMatch(r.phase, p.phase) && globMatch(r.act, p.act) && r.sub == p.sub

[policy_effect]
e = some(where (p.eft == allow))
